export const tableData = [
  {
    id: 1,
    name: 'user',
    email: 'string',
    birthday_date: 'string',
    phone_number: 'string',
    address: 'string',
  },
  {
    id: 2,
    name: 'user',
    email: 'string',
    birthday_date: 'string',
    phone_number: 'string',
    address: 'string',
  },
  {
    id: 3,
    name: 'user',
    email: 'string',
    birthday_date: 'string',
    phone_number: 'string',
    address: 'string',
  },
  {
    id: 4,
    name: 'user',
    email: 'string',
    birthday_date: 'string',
    phone_number: 'string',
    address: 'string',
  },
  {
    id: 1,
    name: 'user',
    email: 'string',
    birthday_date: 'string',
    phone_number: 'string',
    address: 'string',
  },
  {
    id: 4,
    name: 'user',
    email: 'string',
    birthday_date: 'string',
    phone_number: 'string',
    address: 'string',
  },
  {
    id: 5,
    name: 'user',
    email: 'string',
    birthday_date: 'string',
    phone_number: 'string',
    address: 'string',
  },
  {
    id: 6,
    name: 'user',
    email: 'string',
    birthday_date: 'string',
    phone_number: 'string',
    address: 'string',
  },
  {
    id: 7,
    name: 'user',
    email: 'string',
    birthday_date: 'string',
    phone_number: 'string',
    address: 'string',
  },
  {
    id: 8,
    name: 'user',
    email: 'string',
    birthday_date: 'string',
    phone_number: 'string',
    address: 'string',
  },
  {
    id: 9,
    name: 'user',
    email: 'string',
    birthday_date: 'string',
    phone_number: 'string',
    address: 'string',
  },
];
